### ISSUE TITLE
Access processed data

### ISSUE THREAD

**Issue by nathanin** [Yang-Chen-Lab-co/COVID19-scATAC-seq#1]
Hi, can you help me to access the processed data? The baidu link given in the README takes me to a page like this, and I can't figure out how to proceed.

![image](https://user-images.githubusercontent.com/7897122/128583048-f6af6a6c-aab3-4159-99e1-3d0e6a5802e8.png)

Thanks!

**Comment by prete** [comment]
You need to input the password there (`pen7` as mentioned on the README) and then click the blue buttton on the right.

**Comment by nathanin** [comment]
Hi, I didn't notice that before! Thanks I can see the files now, but there's a new question: 

I can't read the website, so I'm guessing here, when I click the download button 
![Screen Shot 2021-08-13 at 1 56 10 PM](https://user-images.githubusercontent.com/7897122/129417918-6ca4e188-5a83-4eb5-8284-928fb13cd6d2.png)
I get this 
![Screen Shot 2021-08-13 at 1 56 36 PM](https://user-images.githubusercontent.com/7897122/129417945-57ca0c08-adc0-4d67-9f0a-4ff7684012aa.png)

that starts to download a file called `BaiduNetdisk_mac_3.9.1.dmg`. Is this a downloader program?

**Comment by Yang-Chen-Lab-co** [comment]
Yes, its a downoader program




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Yang-Chen-Lab-co/COVID19-scATAC-seq"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月14日(星期六) 凌晨5:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Yang-Chen-Lab-co/COVID19-scATAC-seq] Access processed data (#1)





 
Hi, I didn't notice that before! Thanks I can see the files now, but there's a new question:
 
I can't read the website, so I'm guessing here, when I click the download button
 
 I get this
 
 
that starts to download a file called BaiduNetdisk_mac_3.9.1.dmg. Is this a downloader program?
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SaraTerzoli** [comment]
Hi, I have some problems to enter in the downloader program because I have to create an account and I come from italy. Is it possible to create a Baidu account from Italy?

**Comment by Yang-Chen-Lab-co** [comment]
> Hi, I have some problems to enter in the downloader program because I have to create an account and I come from italy. Is it possible to create a Baidu account from Italy?

I noticed that there are some Chinese characters during the downloading and using the baidunetdisk. It will be much convenient and efficient if Chinese people around you can help you.
